/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "api.createDevice": [],
    "api.getDevices": [],
    "api.getDevice": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.updateDevice": [
        {
            "name": "id",
            "required": true
        }
    ],
    "home": [],
    "eletronicos": [],
    "logout": [],
    "contato": [],
    "sobre": [],
    "register": [],
    "registerAction": [],
    "login": [],
    "loginAction": [],
    "dashboard": []
}
}
export {};
